[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200

; Corectarea dimensiunii memoriei pentru a elimina warning-ul si crash-ul
board_build.flash_size = 2MB
board_upload.flash_size = 2MB

